import hashlib
import random
from typing import Optional

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile, status
from sqlalchemy.orm import Session

from ..database import get_db
from ..deps import get_current_user, require_roles
from ..models import AiAnalysis, User

router = APIRouter(prefix="/ai", tags=["ai"])

# No real computer-vision model is wired up here. Results are generated by a
# small rule-based heuristic, seeded from the submitted crop + symptoms text
# so the same input always gives the same answer (rather than being random
# noise). Swap `_diagnose()` for a real model/service call when ready.

_CONDITIONS = [
    ("Early blight", "Fungal", ["Brown concentric spots on lower leaves", "Yellowing around lesions"]),
    ("Powdery mildew", "Fungal", ["White powdery coating on leaves", "Leaf curling"]),
    ("Bacterial leaf spot", "Bacterial", ["Water-soaked spots", "Spots turning dark with yellow halo"]),
    ("Nutrient deficiency (Nitrogen)", "Nutritional", ["Pale/yellow older leaves", "Stunted growth"]),
    ("Healthy — no disease detected", "None", []),
]


def _diagnose(crop: str, symptoms: str):
    seed = int(hashlib.sha256(f"{crop}|{symptoms}".encode()).hexdigest(), 16)
    rng = random.Random(seed)
    condition, cause_type, default_symptoms = rng.choice(_CONDITIONS)
    confidence = round(rng.uniform(0.55, 0.95), 2)
    severity = "None" if condition.startswith("Healthy") else rng.choice(["Low", "Moderate", "High"])
    return condition, cause_type, default_symptoms, confidence, severity


@router.post("/analyze-crop")
async def analyze_crop(
    crop: str = Form(...),
    image: Optional[UploadFile] = File(default=None),
    crop_age: Optional[str] = Form(default=None),
    growth_stage: Optional[str] = Form(default=None),
    location: Optional[str] = Form(default=None),
    symptoms: Optional[str] = Form(default=""),
    irrigation: Optional[str] = Form(default=None),
    additional_information: Optional[str] = Form(default=None),
    user: User = Depends(require_roles("farmer")),
    db: Session = Depends(get_db),
):
    condition, cause_type, default_symptoms, confidence, severity = _diagnose(crop, symptoms or "")

    recommendations = (
        ["No action needed — keep monitoring."]
        if condition.startswith("Healthy")
        else [
            "Remove and destroy visibly affected leaves.",
            "Avoid overhead watering; water at the base instead.",
            "Consider a suitable fungicide/bactericide if symptoms spread.",
        ]
    )
    follow_up = (
        [] if condition.startswith("Healthy")
        else ["Re-check the crop in 5-7 days.", "Request an expert review if symptoms worsen."]
    )

    record = AiAnalysis(
        farmer_id=user.id,
        crop_name=crop,
        diagnosis=condition,
        confidence=confidence,
        status="pending_review",
    )
    db.add(record)
    db.commit()
    db.refresh(record)

    return {
        "success": True,
        "analysis_id": record.id,
        "crop": crop,
        "condition": condition,
        "confidence": confidence,
        "severity": severity,
        "symptoms": [s.strip() for s in (symptoms or "").split(",") if s.strip()] or default_symptoms,
        "possible_causes": [cause_type] if cause_type != "None" else [],
        "recommendations": recommendations,
        "follow_up": follow_up,
    }


@router.get("/analyses")
def list_analyses(user: User = Depends(require_roles("farmer")), db: Session = Depends(get_db)):
    rows = db.query(AiAnalysis).filter(AiAnalysis.farmer_id == user.id).order_by(AiAnalysis.created_at.desc()).all()
    return [
        {
            "id": a.id, "crop": a.crop_name, "diagnosis": a.diagnosis, "confidence": a.confidence,
            "status": a.status, "expert_notes": a.expert_notes, "created_at": a.created_at.isoformat(),
        }
        for a in rows
    ]


@router.get("/analyses/{analysis_id}")
def get_analysis(analysis_id: int, user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    a = db.query(AiAnalysis).get(analysis_id)
    if not a:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Analysis not found.")
    if user.role not in ("admin", "expert") and a.farmer_id != user.id:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="You don't have permission to do this.")
    return {
        "id": a.id, "crop": a.crop_name, "diagnosis": a.diagnosis, "confidence": a.confidence,
        "status": a.status, "expert_notes": a.expert_notes, "created_at": a.created_at.isoformat(),
    }


@router.post("/analyses/{analysis_id}/expert-review")
def request_expert_review(analysis_id: int, payload: dict, user: User = Depends(require_roles("farmer")), db: Session = Depends(get_db)):
    a = db.query(AiAnalysis).get(analysis_id)
    if not a or a.farmer_id != user.id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Analysis not found.")
    a.status = "pending_review"
    db.commit()
    return {"message": "Sent to an expert for review."}


@router.get("/crop-health")
def crop_health(user: User = Depends(get_current_user)):
    return {"summary": "No active alerts.", "recent_analyses": []}


@router.get("/price-prediction")
def price_prediction(crop: Optional[str] = None, user: User = Depends(get_current_user)):
    seed = int(hashlib.sha256((crop or "generic").encode()).hexdigest(), 16)
    rng = random.Random(seed)
    base = rng.uniform(15, 60)
    return {
        "crop": crop or "generic",
        "current_estimate": round(base, 2),
        "trend": rng.choice(["up", "down", "flat"]),
        "next_30_days": [round(base * rng.uniform(0.9, 1.1), 2) for _ in range(4)],
        "note": "Heuristic estimate — no live market-data feed is connected.",
    }


@router.get("/yield-prediction")
def yield_prediction(crop: Optional[str] = None, user: User = Depends(get_current_user)):
    seed = int(hashlib.sha256((crop or "generic").encode()).hexdigest(), 16)
    rng = random.Random(seed)
    return {
        "crop": crop or "generic",
        "estimated_yield_per_acre": round(rng.uniform(8, 25), 1),
        "unit": "quintal",
        "note": "Heuristic estimate — no agronomic model is connected.",
    }


@router.get("/disease-risk")
def disease_risk(crop: Optional[str] = None, user: User = Depends(get_current_user)):
    seed = int(hashlib.sha256((crop or "generic").encode()).hexdigest(), 16)
    rng = random.Random(seed)
    return {"crop": crop or "generic", "risk_level": rng.choice(["Low", "Moderate", "High"]), "note": "Heuristic estimate."}


@router.get("/analytics")
def analytics(user: User = Depends(require_roles("admin")), db: Session = Depends(get_db)):
    total = db.query(AiAnalysis).count()
    pending = db.query(AiAnalysis).filter(AiAnalysis.status == "pending_review").count()
    return {"total_analyses": total, "pending_review": pending}


@router.get("/models")
def models(user: User = Depends(require_roles("admin"))):
    return [{"name": "heuristic-v1", "type": "rule-based", "status": "active"}]
